### ISSUE TITLE
Undici: Connection Timeout with Docker

### ISSUE THREAD

**Issue by imnaiyar** [imnaiyar/SkyHelper#28]
**Describe the bug**
Random connection timeout error while executing live updates/reminders. It's interesting to note that this only happens when hosted with a docker. The behavior doesn't reproduce if hosted normally. Could be the process is getting clogged when looping through multiple guilds (which is a bad idea, I know). A better solution is needed to mitigate the requests (perhaps batching?)

**To Reproduce**
1. Host on docker
2. Wait for a couple of hours
3. See error

**Expected behavior**
For the error to not happen

<details>
<summary> Error </summary>

```bash
ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (/root/skyhelper/node_modules/undici/lib/core/connect.js:190:24)
    at /root/skyhelper/node_modules/undici/lib/core/connect.js:133:46
    at Immediate._onImmediate (/root/skyhelper/node_modules/undici/lib/core/connect.js:174:9)
    at process.processImmediate (node:internal/timers:478:21)
```

**Comment by imnaiyar** [comment]
This may have been already fixed with https://github.com/imnaiyar/SkyHelper/commit/8824f2f394aa51b3fd8795a33bfd6e87d86d9c24
But I'll keep this issue open while I continue to monitor the issue further

**Comment by imnaiyar** [comment]
This doesn't seem to be fixed as of yet

**Comment by imnaiyar** [comment]
Fixed, the solution was updating the Docker version (lol)
